"""Add network_connection field to Log

Revision ID: c1c6227ccd34
Revises: b90a04e96452
Create Date: 2025-03-24 20:15:14.667519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c6227ccd34'
down_revision = 'b90a04e96452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network_connection', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('network_connection')

    # ### end Alembic commands ###
